version: "3"

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    container_name: zookeeper_kafka
    image: docker.io/bitnami/zookeeper:3.8
    networks:
      - app-tier
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: always
    
  kafka:
    image: docker.io/bitnami/kafka:3.1
    networks:
      - app-tier
    container_name: kafka
    restart: always    
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
      - "./kafka_persistence:/bitnami/kafka"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - DUMPPPP=d
    depends_on:
      - zookeeper
  producer:
    container_name: producer
    hostname: viplazy
    image: producer-kafka
    networks:
      - app-tier
    ports:
      - "5056:5056"
    depends_on:
      - kafka
    env_file:
      - .env

  consumer:
    container_name: consumer
    hostname: viplazy
    image: consumer-kafka
    networks:
      - app-tier
    ports:
      - "5057:5057"
    depends_on:
      - kafka
    env_file:
      - .env
    volumes:
      # Path on the host, relative to the Compose file
      - ./flair_model:/root/.flair

  consumer2:
    container_name: consumer2
    hostname: viplazy
    image: consumer-kafka
    networks:
      - app-tier
    ports:
      - "5058:5058"
    depends_on:
      - kafka
    env_file:
      - .env
    volumes:
      # Path on the host, relative to the Compose file
      - ./flair_model:/root/.flair

  consumer3:
    container_name: consumer3
    hostname: viplazy
    image: consumer-kafka
    networks:
      - app-tier
    ports:
      - "5059:5059"
    depends_on:
      - kafka
    env_file:
      - .env
    volumes:
      # Path on the host, relative to the Compose file
      - ./flair_model:/root/.flair

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
